services:
  db:
    image: postgres:15-alpine
    container_name: moni-db
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: moni_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G # Giới hạn RAM cho DB

  app:
    build: .
    container_name: moni-container
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # URL kết nối nội bộ giữa các container
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      NVIDIA_API_KEY: ${NVIDIA_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      ASSEMBLYAI_API_KEY: ${ASSEMBLYAI_API_KEY}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
      DAILY_API_KEY: ${DAILY_API_KEY}
      SEPAY_API_KEY: ${SEPAY_API_KEY}
      APP_PROMPTS_BASE_DIR: /app/prompts
    volumes:
      - ./prompts-data:/app/prompts
    deploy:
      resources:
        limits:
          memory: 2G # Giới hạn RAM cho App

volumes:
  postgres_data: