package io.gsp26se16.moni.tag.entity;

public enum TagType {
    SKILL, // Kỹ năng: Reading, Listening...
    QUESTION_TYPE, // Dạng bài: Multiple Choice, Matching...
    TOPIC, // Chủ đề: Environment, Technology...
    DIFFICULTY // Độ khó: Easy, Medium, Hard
}
