spring:
  application:
    name: moni
  servlet:
    multipart:
      max-file-size: 50MB       # Tăng giới hạn để upload được file Audio dài
      max-request-size: 50MB
  ai:
    openai:
      base-url: https://integrate.api.nvidia.com
      api-key: ${NVIDIA_API_KEY}
      chat:
        options:
          model: meta/llama-3.3-70b-instruct
    vertex:
      ai:
        gemini:
          api-endpoint: ${GEMINI_API_KEY}
          chat:
            options: gemini-3-flash-preview

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-purple-mountain-ah918pfk.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_Lh8S1dtzMNpK
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 300000
      keepalive-time: 60000
      connection-timeout: 10000
      validation-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

cloudinary:
  cloud-name: dolegf6uh
  api-key: 979879863595552
  api-secret: flFglJwtGbWERpADuhpz8oUPA04

outbound:
  identity:
    client-id: 1010429030946-7rpjhtpauni9gim1ihfrbjeh79d21ddc.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:5173


jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij

sepay:
  acc: 21736271
  bank: ACB