#!/usr/bin/env python3
"""
CEFR Vocabulary Import Script
Downloads words.csv from Maximax67/Words-CEFR-Dataset and generates SQL for curated_word table.
Usage:
  python3 import-cefr.py [--csv path/to/words.csv]
  If --csv not provided, attempts to download from GitHub.
"""

import csv
import sys
import os
import argparse

# --- Configuration ---

BAND_MAP = {
    "A1": None,        # Skip A1 (too basic)
    "A2": "3-4",
    "B1": "4-5",
    "B2": "5.5-6.5",
    "C1": "7-8",
    "C2": "8.5-9",
}

# Topic keyword matching (lowercase)
TOPIC_KEYWORDS = {
    "environment": [
        "pollution", "climate", "ecosystem", "forest", "ocean", "carbon",
        "biodiversity", "renewable", "habitat", "wildlife", "greenhouse",
        "emission", "recycle", "deforestation", "drought", "flood",
        "atmosphere", "erosion", "conservation", "sustainable", "ecology",
        "contamination", "pesticide", "ozone", "landfill",
    ],
    "technology": [
        "computer", "digital", "software", "internet", "algorithm",
        "artificial", "robot", "automation", "electronic", "network",
        "cybersecurity", "database", "wireless", "semiconductor", "innovation",
        "prototype", "satellite", "bandwidth", "encryption", "interface",
        "programming", "smartphone", "processor", "virtual", "cloud",
    ],
    "health": [
        "disease", "medical", "therapy", "hospital", "nutrition",
        "vaccine", "diagnosis", "surgery", "mental", "pharmaceutical",
        "chronic", "immune", "symptom", "epidemic", "pandemic",
        "antibiotic", "prescription", "obesity", "diabetes", "cancer",
        "cardiovascular", "neurological", "rehabilitation", "psychology", "stress",
    ],
    "education": [
        "school", "university", "curriculum", "student", "academic",
        "literacy", "pedagogy", "scholarship", "examination", "tuition",
        "graduate", "undergraduate", "classroom", "lecture", "diploma",
        "assessment", "comprehension", "knowledge", "learning", "teaching",
        "cognitive", "institution", "qualification", "vocational", "training",
    ],
    "business": [
        "economy", "market", "profit", "investment", "corporate",
        "entrepreneur", "revenue", "fiscal", "inflation", "recession",
        "merchandise", "commerce", "negotiate", "bankruptcy", "dividend",
        "commodity", "supplier", "logistics", "franchise", "retail",
        "export", "import", "tariff", "tax", "budget",
    ],
    "science": [
        "experiment", "hypothesis", "laboratory", "research", "chemical",
        "molecule", "organism", "evolution", "genetics", "quantum",
        "radioactive", "catalyst", "compound", "periodic", "neutron",
        "photosynthesis", "gravity", "electromagnetic", "thermal", "biology",
        "physics", "chemistry", "astronomy", "microscope", "theory",
    ],
    "travel": [
        "tourist", "destination", "journey", "hotel", "passport",
        "itinerary", "accommodation", "visa", "departure", "arrival",
        "luggage", "customs", "immigration", "expedition", "adventure",
        "sightseeing", "landmark", "cruise", "transit", "reservation",
    ],
    "food": [
        "cuisine", "ingredient", "recipe", "restaurant", "flavor",
        "nutritious", "culinary", "harvest", "beverage", "organic",
        "fermentation", "spice", "dietary", "vegetarian", "vegan",
        "protein", "carbohydrate", "calorie", "appetite", "gastronomy",
    ],
    "society": [
        "community", "culture", "tradition", "population", "urban",
        "immigration", "democracy", "inequality", "poverty", "discrimination",
        "diversity", "ethnicity", "religion", "politics", "governance",
        "parliament", "constitution", "legislation", "census", "sociology",
    ],
    "arts": [
        "music", "painting", "theater", "literature", "creative",
        "sculpture", "poetry", "cinema", "architecture", "photography",
        "choreography", "exhibition", "gallery", "manuscript", "aesthetic",
        "composition", "performance", "narrative", "artistic", "cultural",
    ],
}


def detect_topic(word: str) -> str | None:
    w = word.lower()
    for topic, keywords in TOPIC_KEYWORDS.items():
        if w in keywords:
            return topic
    return None


def escape_sql(s: str) -> str:
    return s.replace("'", "''")


def generate_sql(rows: list[dict]) -> str:
    lines = [
        "-- CEFR Vocabulary Import",
        "-- Generated by import-cefr.py",
        "-- Skips A1 words; maps A2-C2 to IELTS bands",
        "",
        "BEGIN;",
        "",
    ]

    skipped_a1 = 0
    inserted = 0

    for row in rows:
        word = row.get("word", "").strip().lower()
        cefr = row.get("cefr_level", row.get("level", "")).strip().upper()

        if not word or not cefr:
            continue

        band = BAND_MAP.get(cefr)
        if band is None:
            skipped_a1 += 1
            continue  # Skip A1 or unknown

        topic = detect_topic(word)
        topic_sql = f"'{escape_sql(topic)}'" if topic else "NULL"

        lines.append(
            f"INSERT INTO curated_word (word, phonetic, pos, definition, example, meaning, band, cefr_level, topic, audio_url) "
            f"VALUES ('{escape_sql(word)}', NULL, NULL, NULL, NULL, NULL, '{band}', '{cefr}', {topic_sql}, NULL) "
            f"ON CONFLICT DO NOTHING;"
        )
        inserted += 1

    lines.append("")
    lines.append("COMMIT;")
    lines.append("")
    lines.append(f"-- Stats: {inserted} words inserted, {skipped_a1} A1 words skipped")

    return "\n".join(lines)


def load_csv(path: str) -> list[dict]:
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def main():
    parser = argparse.ArgumentParser(description="Generate CEFR SQL import")
    parser.add_argument("--csv", help="Path to words.csv", default=None)
    parser.add_argument("--out", help="Output SQL file", default="cefr-words.sql")
    args = parser.parse_args()

    csv_path = args.csv

    if csv_path is None:
        # Try to download
        import urllib.request
        url = "https://raw.githubusercontent.com/Maximax67/Words-CEFR-Dataset/refs/heads/main/words.csv"
        csv_path = "/tmp/cefr_words.csv"
        print(f"Downloading from {url} ...")
        try:
            urllib.request.urlretrieve(url, csv_path)
        except Exception as e:
            print(f"Download failed: {e}")
            print("Please provide CSV with --csv flag")
            sys.exit(1)

    print(f"Loading CSV from {csv_path} ...")
    rows = load_csv(csv_path)
    print(f"Loaded {len(rows)} rows")

    # Print detected columns
    if rows:
        print(f"Columns: {list(rows[0].keys())}")

    sql = generate_sql(rows)

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), args.out)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"SQL written to {out_path}")


if __name__ == "__main__":
    main()
